-- Run this in the Supabase SQL editor after creating a project.
-- Auth users live in auth.users. App roles and profile data live here.

create table if not exists public.user_profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text unique not null,
  name text not null,
  role text not null default 'user' check (role in ('admin', 'user')),
  is_active boolean not null default true,
  profile_pic text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_profiles enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_profiles
    where email = auth.jwt() ->> 'email'
      and role = 'admin'
  );
$$;

grant execute on function public.is_admin() to authenticated;

create policy "Users can read their own profile"
  on public.user_profiles
  for select
  to authenticated
  using (auth.uid() = id or email = auth.jwt() ->> 'email');

drop policy if exists "Admins can read all profiles" on public.user_profiles;
create policy "Admins can read all profiles"
  on public.user_profiles
  for select
  to authenticated
  using (public.is_admin());

create policy "Users can insert their own profile"
  on public.user_profiles
  for insert
  to authenticated
  with check (auth.uid() = id);

-- Live user_profiles.id is bigint; auth.uid() is uuid. Never compare the two
-- (22P02). Match the signed-in email instead, same as address RLS.
drop policy if exists "Users can update their own profile" on public.user_profiles;
create policy "Users can update their own profile"
  on public.user_profiles
  for update
  to authenticated
  using (email = auth.jwt() ->> 'email')
  with check (email = auth.jwt() ->> 'email');

drop policy if exists "Admins can insert profiles" on public.user_profiles;
create policy "Admins can insert profiles"
  on public.user_profiles
  for insert
  to authenticated
  with check (public.is_admin());

drop policy if exists "Admins can update all profiles" on public.user_profiles;
create policy "Admins can update all profiles"
  on public.user_profiles
  for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "Admins can delete profiles" on public.user_profiles;
create policy "Admins can delete profiles"
  on public.user_profiles
  for delete
  to authenticated
  using (public.is_admin());

create or replace function public.protect_user_profile_fields()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if public.is_admin() then
    return NEW;
  end if;
  NEW.role := OLD.role;
  NEW.is_active := OLD.is_active;
  NEW.email := OLD.email;
  return NEW;
end;
$$;

drop trigger if exists protect_user_profile_fields on public.user_profiles;
create trigger protect_user_profile_fields
  before update on public.user_profiles
  for each row
  execute function public.protect_user_profile_fields();

-- Promote a user to admin after they register:
-- update public.user_profiles set role = 'admin' where email = 'you@example.com';

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text not null default '',
  created_at timestamptz not null default now()
);

alter table public.categories
  add column if not exists description text not null default '';

alter table public.categories enable row level security;

create policy "Authenticated users can read categories"
  on public.categories
  for select
  to authenticated
  using (true);

create policy "Authenticated users can insert categories"
  on public.categories
  for insert
  to authenticated
  with check (true);

-- Live project uses bigint ids on user_profiles and address (not auth UUIDs).
-- Do not compare auth.uid() to those columns; that raises 22P02.

create table if not exists public.address (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.user_profiles (id) on delete cascade,
  name text not null,
  phone text not null,
  address_line text not null,
  city text not null,
  state text not null,
  postal_code text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.address
  add column if not exists is_default boolean not null default false;

alter table public.address enable row level security;

drop policy if exists "Users can read their own addresses" on public.address;
drop policy if exists "Users can insert their own addresses" on public.address;
drop policy if exists "Users can update their own addresses" on public.address;
drop policy if exists "Users can delete their own addresses" on public.address;

create policy "Users can read their own addresses"
  on public.address
  for select
  to authenticated
  using (
    user_id = (
      select p.id
      from public.user_profiles p
      where p.email = auth.jwt() ->> 'email'
      limit 1
    )
    or public.is_admin()
  );

create policy "Users can insert their own addresses"
  on public.address
  for insert
  to authenticated
  with check (
    user_id = (
      select p.id
      from public.user_profiles p
      where p.email = auth.jwt() ->> 'email'
      limit 1
    )
  );

create policy "Users can update their own addresses"
  on public.address
  for update
  to authenticated
  using (
    user_id = (
      select p.id
      from public.user_profiles p
      where p.email = auth.jwt() ->> 'email'
      limit 1
    )
  )
  with check (
    user_id = (
      select p.id
      from public.user_profiles p
      where p.email = auth.jwt() ->> 'email'
      limit 1
    )
  );

create policy "Users can delete their own addresses"
  on public.address
  for delete
  to authenticated
  using (
    user_id = (
      select p.id
      from public.user_profiles p
      where p.email = auth.jwt() ->> 'email'
      limit 1
    )
  );

-- Live project uses bigint ids on user_profiles and address.
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  user_id bigint not null references public.user_profiles (id) on delete cascade,
  subtotal numeric not null,
  shipping_fee numeric not null default 0,
  total numeric not null,
  status text not null default 'pending'
    check (status in ('pending', 'paid', 'shipped', 'delivered', 'cancelled')),
  payment_id text unique,
  items jsonb not null default '[]'::jsonb,
  address_id bigint not null references public.address (id)
);

alter table public.orders enable row level security;

drop policy if exists "Users can read their own orders" on public.orders;
drop policy if exists "Admins can read all orders" on public.orders;
drop policy if exists "Users can insert their own orders" on public.orders;
drop policy if exists "Users can update their own orders" on public.orders;
drop policy if exists "Admins can update all orders" on public.orders;

create policy "Users can read their own orders"
  on public.orders
  for select
  to authenticated
  using (
    user_id = (
      select p.id
      from public.user_profiles p
      where p.email = auth.jwt() ->> 'email'
      limit 1
    )
    or exists (
      select 1
      from public.user_profiles p
      where p.email = auth.jwt() ->> 'email'
        and p.role = 'admin'
    )
  );

create policy "Users can insert their own orders"
  on public.orders
  for insert
  to authenticated
  with check (
    user_id = (
      select p.id
      from public.user_profiles p
      where p.email = auth.jwt() ->> 'email'
      limit 1
    )
  );

create policy "Users can update their own orders"
  on public.orders
  for update
  to authenticated
  using (
    user_id = (
      select p.id
      from public.user_profiles p
      where p.email = auth.jwt() ->> 'email'
      limit 1
    )
    or exists (
      select 1
      from public.user_profiles p
      where p.email = auth.jwt() ->> 'email'
        and p.role = 'admin'
    )
  )
  with check (
    user_id = (
      select p.id
      from public.user_profiles p
      where p.email = auth.jwt() ->> 'email'
      limit 1
    )
    or exists (
      select 1
      from public.user_profiles p
      where p.email = auth.jwt() ->> 'email'
        and p.role = 'admin'
    )
  );
